@host= http://localhost:5146
@content_type = application/json

###

POST {{host}}/bible/categories
content-type: {{content_type}}

{
    "id":                   "",
    "categoryName" :        "string",
    "categoryDescription" : "string"
}